In [ ]:
# 글자크기가 제한되는 유니코드 스트링...........
# 키워드 인수 dtype=''
# np.nan은 SQL에서의 NULL값과 같다

In [1]:
# 넘파이 패키지 임포트하기!!! 중요

import numpy as np

In [2]:
# 1차원 배열 만들기
# ndarray()로 생성한 객체는 numpy.ndarray 타입을 갖는다.

ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
ar.shape

# 1차원의 10칸 갖는 ndarray

(10,)

In [4]:
type(ar)

numpy.ndarray

In [5]:
ar2 = np.array([1.1, 5, 4, 12, 0.5])
ar2

# 아래 정수 뒤에 .쩜 이 찍혀있네? 표현범위가 더 넓은 자료형으로 통일이 되기 때문
# 실수의 표현범위가 더 넓기 때문이다.

array([ 1.1,  5. ,  4. , 12. ,  0.5])

In [6]:
# 넘파이의 자료형
# 넘파이의 배열인 ndarray클래스는 요소가 모두 같은 자료형을 가짐
# dtype

In [7]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [8]:
# ndarray도 인덱싱을 할 수 있다
x[0] + x[1]

3.0

In [9]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [10]:
x[0] + x[1]

'12'

In [11]:
# x = [0, 1, -1, 0]
# y = [1, 0, 0, 0]
# x/y

# 리스트는 나누기 연산이 안된다. 그러나 넘파이는...

In [12]:
# 벡터화 연산(Vectorized Operation)
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
answer = [2 * d for d in data]

In [14]:
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
a = [1, 2, 3]
b = [10, 20, 30]

In [18]:
2 * a+b

[1, 2, 3, 1, 2, 3, 10, 20, 30]

In [19]:
an = np.array(a)
bn = np.array(b)

In [20]:
2 * an + bn

array([12, 24, 36])

In [21]:
an

array([1, 2, 3])

In [22]:
an == 2        # 결과값 True False 갖는거 기억. 중요!!!

# b > 0 불리언 인덱싱 할 수 있다. b[b > 10] 이후 필터링까지 배울 예정

array([False,  True, False])

In [23]:
bn > 10        # 결과값 True False 갖는거 기억. 중요!!!

array([False,  True,  True])

In [24]:
# 비교연산자 여러개일 때 소괄호 잊지말기!!! (우선순위)
# (a == 2) & (b > 10)

In [25]:
# 사실 통상적으로(?) True == 1, False == 0 값을 갖는다.
# &는  and 연산이랑 똑같다?? (앞이 True이고 뒤가 True일때 True 값을 갖는)
# (물론 동작하는 것은 다름)
# NumPy에서는 and 사용하면 오류가 나서 &(앰퍼샌드)를 대신 사용한다.
# & 사용할 때는 연산자 우선순위 유의해서 소괄호 사용한 것.

(an == 2) & (bn > 10)

array([False,  True, False])

In [26]:
c = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
c

# 2차원은 리스트에 리스트를......사용함

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
c.shape

(2, 3)

In [28]:
len(c) # 행의 갯수

2

In [29]:
len(c[0]) # 열의 갯수

3

In [30]:
n = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
n

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [31]:
d = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 15]],[[11, 12, 13, 14],[15, 16, 17, 18],[19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 15]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [32]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [33]:
d.shape

(2, 3, 4)

In [34]:
a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [35]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [36]:
test = [[1, 2, 3, 4], [5, 6, 7, 8]] #List

In [37]:
test[1][1]

6

In [38]:
a = np.array([[0, 1, 2],[3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
a[0, 0]

0

In [40]:
a = [[1, 2, 3, 4], [5, 6, 7, 8]] #List

In [41]:
a[0][0:3] # a에서 1, 2, 3의 값을 가져오기

[1, 2, 3]

In [42]:
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
a[0, :]

array([0, 1, 2, 3])

In [44]:
a[:, 1]

array([1, 5])

In [45]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [46]:
m[1, 2]

7

In [47]:
m[2, 4]

14

In [48]:
m[1, 1:3]

array([6, 7])

In [49]:
m[1:, 2]

array([ 7, 12])

In [50]:
m[:2 ,3:]

array([[3, 4],
       [8, 9]])

In [51]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [52]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [53]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [54]:
d[0]= 'abc'
d[1]= 'abcd'
d[2]= 'ABCD'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [55]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [56]:
f = np.ones_like(b, dtype="f")
f

array([1., 1., 1.], dtype=float32)

In [57]:
g = np.empty((4, 3))
g

array([[7.53957703e-312, 2.86558075e-322, 0.00000000e+000],
       [0.00000000e+000, 1.08221785e-312, 1.16095484e-028],
       [3.74168445e+233, 3.10573437e-115, 4.07175422e+223],
       [6.32672800e+180, 4.74483502e+170, 8.47093531e-053]])

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [60]:
ex = np.linspace(0, 100, 5)
ex

array([  0.,  25.,  50.,  75., 100.])

In [61]:
ex2 = np.logspace(0, 100, 5)  
ex2
# 로그범위가 동일하게....

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [62]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
A.T # 전치연산

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
b = a.reshape(3, 4) # 배열의 크기 변형. 모양 변경
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
a.reshape(3, -1) # ??? -1 뭐지??

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a.reshape(2, 2, -1)  # ???

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [68]:
a.reshape(2, -1, 2) # ???

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [69]:
a.flatten() # 다차원 배열 --> 1차원 배열 flatten or ravel 메서드 사용
# 쭉 펴서 1치원으로 만드는......

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [72]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [73]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [74]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [75]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [77]:
np.hstack([a1, a2]) 
# 행의 수가 같은 두 개 이상의 배열을 옆으로 연결
# 수평하게 나란히.

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [78]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.vstack([b1, b2]) 
# 열의 수가 같은 두개 이상의 배열을 위아래로 연결

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
# 깊이 방향으로 행열을 합침

c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
np.dstack([c1, c2]) 
# shape의 젤 안쪽을 합친다.

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [84]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [85]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [86]:
c.shape

(2, 3, 4)

In [87]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [88]:
c.shape

(3, 2, 4)

In [89]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]
# 알 언더바 인덱서인데 이렇게 합해줌

array([1, 2, 3, 4, 5, 6])

In [90]:
# c_ 메서드는 배열의 차원을 증가시킨 후 좌우로 연결 대괄호사용!!

np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [92]:
# tile 틸 명령은 동일한 배열을 반복하여 연결

np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [93]:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [94]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [95]:
c = np.hstack([a, b])

In [96]:
d = np.arange(10, 151, 10).reshape(3, 5)

In [97]:
e = np.vstack([c, d])

In [98]:
f = np.tile(e,(2, 1))
f

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [99]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [100]:
a == b

array([False,  True, False,  True])

In [101]:
a >= b

array([False,  True,  True,  True])

In [102]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [103]:
np.all(a == b) 
# .all은 괄호 안에 오는 요소가 모두 트루일 때만 트루를 반환.

False

In [104]:
np.all(a == c)

True

In [105]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [107]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [109]:
# 브로드캐스팅

a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [110]:
# sum()
# 해당 배열의 합산 결과를 반환. 2차원 이상일 때 axis 키워드 인수 사용 가능

x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [111]:
np.sum(x)

10

In [112]:
x.sum()

10

In [113]:
x = np.arange(12).reshape(3, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
x.sum(axis=0)

array([12, 15, 18, 21])

In [115]:
x.sum(axis=1)

array([ 6, 22, 38])

In [116]:
x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [117]:
x.min()

0

In [118]:
np.min(x)

0

In [119]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [120]:
np.min(x, axis=1)

array([[ 0,  1],
       [10, 11]])

In [121]:
x.min(axis=2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [122]:
x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [123]:
x.argmin()

0

In [124]:
np.argmin(x)

0

In [125]:
x.argmin(axis=0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [126]:
np.argmin(x, axis=1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [127]:
x.argmin(axis=2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [128]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                                [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                                [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                                [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                                [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [129]:
practice.max()

9.0

In [130]:
practice.sum(axis=0)  # axis = 0 행 간

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [131]:
practice.max(axis=0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [132]:
practice.mean(axis=1) # axis = 1 열 간 ///// 평균을 구함

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [133]:
practice.min(axis=1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

In [134]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)   #오름차순으로 인덱스를 가져온 것
j

array([2, 3, 1, 0], dtype=int64)

In [135]:
a[j]

array([12, 25, 38, 42])

In [136]:
np.sort(a)

array([12, 25, 38, 42])

In [137]:
a = np.array([[1, 2],[3, 4],[5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [138]:
# 고급 인덱싱 - 인덱스 배열을 사용한 인덱싱

print(a[[0, 1, 2],[0, 1, 0]])

# a[0,0] a[1,1] a[2,0]을 인덱스로 하는 1차원 배열 (shape=(3,))을 출력해줌

[1 4 5]


In [139]:
scores = np.array([[1, 2, 3, 4],
                   [46, 99, 100, 71],
                   [81, 59, 90, 100]])

In [140]:
s = np.argsort(scores[1,:]) # 순서를 알고싶을 때
s

array([0, 3, 1, 2], dtype=int64)

In [141]:
print(scores[:,s])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [142]:
np.random.seed(0)      # 난수 발생

In [143]:
result = np.random.randint(0, 2, 100)
result

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [144]:
np.mean(result)

0.56

In [ ]:
# 분산은 var 표준편차는 std....... 