In [1]:
import numpy as np

In [2]:
np.random.seed(0) 
result = np.random.randint(1, 7, 100)
print(result)
np.mean(result)

[5 6 1 4 4 4 2 4 6 3 5 1 1 5 3 2 1 2 6 2 6 1 2 5 4 1 4 6 1 3 4 1 2 4 6 4 4
 1 2 2 2 1 3 5 4 4 3 5 3 1 1 5 6 6 1 5 2 5 2 3 3 1 2 2 2 2 4 4 3 4 1 4 6 5
 2 3 5 4 5 5 5 4 5 5 5 1 5 4 3 6 6 6 1 2 6 2 4 1 6 1]


3.42

In [3]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[7, 8, 9],[10, 11, 12]])
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [4]:
c = np.arange(1,10)
c * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [65]:
f = np.zeros(10)
f[4]=1
print(f)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [67]:
v = np.arange(50)
v[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [69]:
np.zeros((3, 3, 3), dtype='U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [5]:
x = np.arange(2,41,2).reshape(2,2,5)
x

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [6]:
# np.full(shape, fill_value, dtype=None, order='C', *, like=None)

import numpy as np
np.full((3, 3, 3), 'playdata', dtype='U10')

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U10')

In [7]:
# np.eye(n) 

np.eye(4)   

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
# ndarray.astype
np.random.seed(0) 

In [9]:
a = np.random.randint(0, 2, 9)
a

array([0, 1, 1, 0, 1, 1, 1, 1, 1])

In [10]:
a.astype('bool').reshape(3, 3)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [11]:
np.random.seed(0) 

In [12]:
b = np.random.rand(10) * 10
b

array([5.48813504, 7.15189366, 6.02763376, 5.44883183, 4.23654799,
       6.45894113, 4.37587211, 8.91773001, 9.63662761, 3.83441519])

In [13]:
result = b.astype('i') # 타입을 변경한다.
result

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [ ]:
# False = 0 이고 True = 1 인 것을 꼭 기억합시다!!!

# 불리언 인덱싱 중요합니데이!!!!!

In [14]:
n = np.ones((10,10))
n[1:9,1:9] = 0
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
n = np.ones((10,10))
n[:1] = 0
n[9:10] = 0
n[1:-1,0]=0
n[1:-1,-1]=0
print(n)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
n = np.ones((10,10))
n[:,[0,-1]] = 0
n[[0,-1],:] = 0
print(n)

# 선생님 풀이

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
m = np.ones((8,8))       # 하 정말 어려웠다
m[0::2,1::2] = 0    
m[1::2,0::2] = 0
result = m.astype('i')
print(result)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [18]:
m = np.ones((8,8), dtype = int)        # 쌤 풀이
m[0::2,1::2] = 0    
m[1::2,0::2] = 0
print(result)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [19]:
f = np.array([[1, 0], [0, 1]])
np.tile(f, (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [20]:
a = np.arange(11)
result = np.array([True if 3<i<7 else False for i in a])
a[result] = -a[result]
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [21]:
z = np.arange(1,101)
result = np.array([True if i % 3 == 0 else False for i in z])
sum(z[result])

1683

In [22]:
f = np.linspace(0.1, 0.9, 9)
f

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [35]:
while True:
    try:
        number = int(input())
        if number>0:
            for _ in range(number):
                result = np.random.choice(range(1, 46), size=6, replace=False)
                # 비복원추출 중복을 피한다는 의미. choice와 replace 사용
                result.sort()   # 오름차순
                print(result)
            break
        else:
            print("자연수만 입력해주세요.")
    except ValueError:
        print("자연수만 입력해주세요.")
        continue

 -3


자연수만 입력해주세요.


 -5


자연수만 입력해주세요.


 -9


자연수만 입력해주세요.


 3


[27 31 37 42 43 45]
[ 9 20 25 36 37 40]
[ 6  8 32 33 37 38]


In [34]:
resp_time = np. array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
199, 55, 151, 183, 152, 119, 193, 110, 204])

result = np.array([True if i>200 else False for i in resp_time])
len(resp_time[result])

#(resp_time > 200).sum() 선생님 풀이.....넘나 간단하고 좋으네여....

8

In [43]:
resp_time = np. array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
199, 55, 151, 183, 152, 119, 193, 110, 204])

result1 = np.percentile(resp_time, 0)
result2 = np.percentile(resp_time, 25)
result3 = np.percentile(resp_time, 50)
result4 = np.percentile(resp_time, 75)
result5 = np.percentile(resp_time, 100)
display(result1, result2, result3, result4, result5)

# enumerate --> index(i) 값과 value(v)값을 동시에 준다
# for i, v in enumerate(range(25, 76, 25)):
# print(f'{})  으악 필기 놓침 선생님 답

# np.quantile(resp_time, 0.75) 기영이 답

4.0

71.5

131.0

175.5

218.0

In [47]:
# 학생 회장 선거에서 뽀로로가 0번, 루피가 1번, 크롱이 2번일 때 누가 몇표로 학생 회장에 
# 당선되었는지 확인해보세요.
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])

In [56]:
a, b = np.unique(result, return_counts=True)
winner = b.argmax()
print(f"{p[winner]}가 {np.max(b)}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.
